---
- name: "Replace certificate lines in vhost file {{ certbot_modify_vhost_file }}"
  replace:
    path: "{{ certbot_modify_vhost_file }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - regexp: '(SSLCertificateFile )(.*)$'
      replace: '\1/etc/letsencrypt/live/{{ certbot_cert_domain_folder_name }}/cert.pem'
    - regexp: '(SSLCertificateKeyFile )(.*)$'
      replace: '\1/etc/letsencrypt/live/{{ certbot_cert_domain_folder_name }}/privkey.pem'
  when: certbot_modify_vhost_file is defined and certbot_modify_vhost_file

- name: Restart services
  service:
    name: "{{ item }}"
    state: restarted
  with_items: "{{ certbot_restart_services_on_completion }}"
